<?xml version="1.0" encoding="utf-8"?><Database Name="TT 2019-A071" Class="BDControlCambioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=tt-a071-controldecambio.database.windows.net;Initial Catalog=&quot;TT 2019-A071&quot;;Persist Security Info=True;User ID=EnriqueHdez" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TT_2019_A071ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Actividades" Member="Actividades">
    <Type Name="Actividades">
      <Column Name="Id_Ac" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FechaRealizacion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Observaciones" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Responsable" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Actividades_ActividadesControl" Member="ActividadesControl" ThisKey="Id_Ac" OtherKey="fk_Ac" Type="ActividadesControl" />
      <Association Name="Usuario_Actividades" Member="Usuario" ThisKey="Responsable" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActividadesControl" Member="ActividadesControl">
    <Type Name="ActividadesControl">
      <Column Name="Id_CA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_Ac" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Actividades_ActividadesControl" Member="Actividades" ThisKey="fk_Ac" OtherKey="Id_Ac" Type="Actividades" IsForeignKey="true" />
      <Association Name="ControlCambio_ActividadesControl" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Autorizaciones" Member="Autorizaciones">
    <Type Name="Autorizaciones">
      <Column Name="Id_Au" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_U" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Autorizado" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ControlCambio_Autorizaciones" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
      <Association Name="Usuario_Autorizaciones" Member="Usuario" ThisKey="fk_U" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ControlCambio" Member="ControlCambio">
    <Type Name="ControlCambio">
      <Column Name="Id_CC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FechaEjecucion" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Introduccion" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Objetivos" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Creador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlCambio_ActividadesControl" Member="ActividadesControl" ThisKey="Id_CC" OtherKey="fk_CC" Type="ActividadesControl" />
      <Association Name="ControlCambio_Autorizaciones" Member="Autorizaciones" ThisKey="Id_CC" OtherKey="fk_CC" Type="Autorizaciones" />
      <Association Name="ControlCambio_ControlServicio" Member="ControlServicio" ThisKey="Id_CC" OtherKey="fk_CC" Type="ControlServicio" />
      <Association Name="ControlCambio_Documentos" Member="Documentos" ThisKey="Id_CC" OtherKey="fk_CC" Type="Documentos" />
      <Association Name="ControlCambio_Notificaciones" Member="Notificaciones" ThisKey="Id_CC" OtherKey="fk_CC" Type="Notificaciones" />
      <Association Name="ControlCambio_Revisiones" Member="Revisiones" ThisKey="Id_CC" OtherKey="fk_CC" Type="Revisiones" />
      <Association Name="ControlCambio_Riesgos" Member="Riesgos" ThisKey="Id_CC" OtherKey="fk_CC" Type="Riesgos" />
      <Association Name="Usuario_ControlCambio" Member="Usuario" ThisKey="Creador" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ControlServicio" Member="ControlServicio">
    <Type Name="ControlServicio">
      <Column Name="Id_CS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_SA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FechaInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FechaFinal" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ControlCambio_ControlServicio" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
      <Association Name="ServiciosAplicaciones_ControlServicio" Member="ServiciosAplicaciones" ThisKey="fk_SA" OtherKey="Id_SA" Type="ServiciosAplicaciones" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documentos" Member="Documentos">
    <Type Name="Documentos">
      <Column Name="Id_Do" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocPath" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlCambio_Documentos" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Monitoreo" Member="Monitoreo">
    <Type Name="Monitoreo">
      <Column Name="Id_At" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fk_U" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuario_Monitoreo" Member="Usuario" ThisKey="fk_U" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notificaciones" Member="Notificaciones">
    <Type Name="Notificaciones">
      <Column Name="Id_No" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Contenido" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="FechaEnvio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fk_U" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlCambio_Notificaciones" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
      <Association Name="Usuario_Notificaciones" Member="Usuario" ThisKey="fk_U" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Revisiones" Member="Revisiones">
    <Type Name="Revisiones">
      <Column Name="Id_Re" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="InfGeneral" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Actividades" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Riesgos" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Servicios" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlCambio_Revisiones" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Riesgos" Member="Riesgos">
    <Type Name="Riesgos">
      <Column Name="Id_Ri" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Tipo" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="fk_CC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ControlCambio_Riesgos" Member="ControlCambio" ThisKey="fk_CC" OtherKey="Id_CC" Type="ControlCambio" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Roles">
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Roles_UsuarioRol" Member="UsuarioRol" ThisKey="Id_Rol" OtherKey="fk_Rol" Type="UsuarioRol" />
    </Type>
  </Table>
  <Table Name="dbo.ServiciosAplicaciones" Member="ServiciosAplicaciones">
    <Type Name="ServiciosAplicaciones">
      <Column Name="Id_SA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Acronimo" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Dueno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ServiciosAplicaciones_ControlServicio" Member="ControlServicio" ThisKey="Id_SA" OtherKey="fk_SA" Type="ControlServicio" />
      <Association Name="Usuario_ServiciosAplicaciones" Member="Usuario" ThisKey="Dueno" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="Id_U" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApePaterno" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ApeMaterno" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(45) NOT NULL" CanBeNull="false" />
      <Column Name="NoExt" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="Activo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ClaveUnica" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Actividades" Member="Actividades" ThisKey="Id_U" OtherKey="Responsable" Type="Actividades" />
      <Association Name="Usuario_Autorizaciones" Member="Autorizaciones" ThisKey="Id_U" OtherKey="fk_U" Type="Autorizaciones" />
      <Association Name="Usuario_ControlCambio" Member="ControlCambio" ThisKey="Id_U" OtherKey="Creador" Type="ControlCambio" />
      <Association Name="Usuario_Monitoreo" Member="Monitoreo" ThisKey="Id_U" OtherKey="fk_U" Type="Monitoreo" />
      <Association Name="Usuario_Notificaciones" Member="Notificaciones" ThisKey="Id_U" OtherKey="fk_U" Type="Notificaciones" />
      <Association Name="Usuario_ServiciosAplicaciones" Member="ServiciosAplicaciones" ThisKey="Id_U" OtherKey="Dueno" Type="ServiciosAplicaciones" />
      <Association Name="Usuario_UsuarioRol" Member="UsuarioRol" ThisKey="Id_U" OtherKey="fk_Us" Type="UsuarioRol" />
    </Type>
  </Table>
  <Table Name="dbo.UsuarioRol" Member="UsuarioRol">
    <Type Name="UsuarioRol">
      <Column Name="Id_UR" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="fk_Us" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fk_Rol" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Roles_UsuarioRol" Member="Roles" ThisKey="fk_Rol" OtherKey="Id_Rol" Type="Roles" IsForeignKey="true" />
      <Association Name="Usuario_UsuarioRol" Member="Usuario" ThisKey="fk_Us" OtherKey="Id_U" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
</Database>